//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(AppointmentSlotMetaData))]
    public partial class AppointmentSlot
    {
    internal sealed class AppointmentSlotMetaData
    {
    public int AppointmentSlotsID { get; set; }
    
    public Nullable<int> DoctorID { get; set; }
    
    [StringLength(50, ErrorMessage="SlotFrom should be less than 50 characters")]
    public string SlotFrom { get; set; }
    
    [StringLength(50, ErrorMessage="SlotTo should be less than 50 characters")]
    public string SlotTo { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> AddedOn { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    
    public Nullable<bool> isdeleted { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> SlotFromDateTime { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> SlotToDateTime { get; set; }
    
    }
    }
}
