//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(DoctorAppointmentScheduleMetaData))]
    public partial class DoctorAppointmentSchedule
    {
    internal sealed class DoctorAppointmentScheduleMetaData
    {
    public int ScheduleId { get; set; }
    
    public Nullable<int> DoctorID { get; set; }
    
    public Nullable<int> AppointmentSlotID { get; set; }
    
    [StringLength(100, ErrorMessage="Timings_Slot should be less than 100 characters")]
    public string Timings_Slot { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> AddedOn { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    
    public Nullable<bool> isdeleted { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> SlotFromDateTime { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> SlotToDateTime { get; set; }
    
    }
    }
}
