//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(FeedbackMetaData))]
    public partial class Feedback
    {
    internal sealed class FeedbackMetaData
    {
    public int FeedbackId { get; set; }
    
    [StringLength(255, ErrorMessage="FeedbackText should be less than 255 characters")]
    public string FeedbackText { get; set; }
    
    public int DoctorId { get; set; }
    
    public int PatientId { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> AddedOn { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    
    }
    }
}
