//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(HospitalMetaData))]
    public partial class Hospital
    {
    internal sealed class HospitalMetaData
    {
    public int HospitalId { get; set; }
    
    [StringLength(20, ErrorMessage="HospitalDisplayId should be less than 20 characters")]
    public string HospitalDisplayId { get; set; }
    
    [StringLength(255, ErrorMessage="Name should be less than 255 characters")]
    [Required(ErrorMessage="Name is required")]
    public string Name { get; set; }
    
    public Nullable<bool> IsActive { get; set; }
    
    [StringLength(100, ErrorMessage="AddressLine1 should be less than 100 characters")]
    public string AddressLine1 { get; set; }
    
    [StringLength(100, ErrorMessage="AddressLine2 should be less than 100 characters")]
    public string AddressLine2 { get; set; }
    
    [StringLength(20, ErrorMessage="City should be less than 20 characters")]
    public string City { get; set; }
    
    [StringLength(20, ErrorMessage="State should be less than 20 characters")]
    public string State { get; set; }
    
    [DataType(DataType.PostalCode)]
    public Nullable<int> ZipCode { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> AddedOn { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    
    public byte[] ImageContent { get; set; }
    
    }
    }
}
