//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public MedicalRecord()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int MedicalRecordId { get; set; }
        public string MedicalRecordName { get; set; }
        public byte[] MedicalRecordImage { get; set; }
        public string ImageExtension { get; set; }
        public int PatientId { get; set; }
        public int HospitalId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AddedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
