//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(PatientNotificationMetaData))]
    public partial class PatientNotification
    {
    internal sealed class PatientNotificationMetaData
    {
    public int PatientNotificationId { get; set; }
    
    [StringLength(255, ErrorMessage="NotificationText should be less than 255 characters")]
    public string NotificationText { get; set; }
    
    [Required(ErrorMessage="Notification Time is required")]
    [DataType(DataType.DateTime)]
    public System.DateTime NotificationTime { get; set; }
    
    public int PatientId { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> AddedOn { get; set; }
    
    [DataType(DataType.DateTime)]
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    
    }
    }
}
