//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(RoleMetaData))]
    public partial class Role
    {
    internal sealed class RoleMetaData
    {
    public int RoleId { get; set; }
    
    [StringLength(20, ErrorMessage="Name should be less than 20 characters")]
    public string Name { get; set; }
    
    [StringLength(50, ErrorMessage="Description should be less than 50 characters")]
    public string Description { get; set; }
    
    }
    }
}
