//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(StateMetaData))]
    public partial class State
    {
    internal sealed class StateMetaData
    {
    public int StateId { get; set; }
    
    [Required(ErrorMessage="State Name is required")]
    public string StateName { get; set; }
    
    public int CountryId { get; set; }
    
    }
    }
}
