//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(SubRegionMetaData))]
    public partial class SubRegion
    {
    internal sealed class SubRegionMetaData
    {
    public int SubRegionId { get; set; }
    
    [Required(ErrorMessage="Sub Region Name is required")]
    public string SubRegionName { get; set; }
    
    public int DistrictId { get; set; }
    
    }
    }
}
