//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareDataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(sysdiagramMetaData))]
    public partial class sysdiagram
    {
    internal sealed class sysdiagramMetaData
    {
    [StringLength(128, ErrorMessage="name should be less than 128 characters")]
    [Required(ErrorMessage="name is required")]
    public string name { get; set; }
    
    public int principal_id { get; set; }
    
    public int diagram_id { get; set; }
    
    public Nullable<int> version { get; set; }
    
    public byte[] definition { get; set; }
    
    }
    }
}
